# Generated by Django 5.1.2 on 2024-11-12 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_projects_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='challenges',
            field=models.TextField(default='Chellenging'),
            preserve_default=False,
        ),
    ]
